# If rakfefile not ofund 
language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t xjacky2wong/docker-react -f Dockerfile.dev . 

# Because jest library has changed, we use: 
script:
  # - docker run -e CI=true xjacky2wong/docker-react npm run test -- --coverage
  - docker run -e CI=true xjacky2wong/docker-react npm run test
deploy:
  edge: true
  provider: elasticbeanstalk
  region: "ap-southeast-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-ap-southeast-2-496898353521"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: 
    secure: "Encrypted $AWS_ACCESS_KEY"
  secret_access_key: 
    secure: "Encrypted $AWS_SECRET_KEY"